Regional copy implementation for transfers
gigabit-clowns/xmipp4-compute-cuda pull request #4
Opened 2024-11-11 18:01 UTC by oierlauzi

Merge after:
https://github.com/gigabit-clowns/xmipp4-core/pull/79

2024-11-11 20:54 UTC, MartinSalinas98 requested changes

2024-11-11 20:54 UTC, MartinSalinas98 commented on src/compute/cuda/cuda_host_to_device_transfer.cpp
> +        }
Extract comparison with exception to a function in core

2024-11-11 20:54 UTC, MartinSalinas98 commented on src/compute/cuda/cuda_host_to_device_transfer.cpp
> +    }
Extract to a function in core

2024-11-12 11:38 UTC, oierlauzi commented
Re-run actions after:
https://github.com/gigabit-clowns/xmipp4-core/pull/82

2024-11-12 13:32 UTC, MartinSalinas98 approved these changes

2024-11-12 13:36 UTC, merged