Implemented synchronization interface
gigabit-clowns/xmipp4-compute-cuda pull request #7
Opened 2024-11-13 16:57 UTC by oierlauzi

Implemented synchronization interface from https://github.com/gigabit-clowns/xmipp4-core/pull/83. Do not merge until that PR is merged.

In CUDA all syncronization operations can be performed by a `cudaEvent_t`, so a single class implements all three interfaces.

2024-11-13 17:27 UTC, oierlauzi commented
Re-run actions when core PR is merged

2024-11-18 18:34 UTC, MartinSalinas98 commented on src/compute/cuda/cuda_device_buffer_copy.cpp
> +        dynamic_cast<cuda_device_buffer&>(dst_buffer).get_data();
Consistency: asterisk to the right of the declaration

2024-11-18 19:04 UTC, MartinSalinas98 requested changes

2024-11-18 19:04 UTC, MartinSalinas98 commented on src/compute/cuda/cuda_device.hpp
> +    create_device_buffer_copy() override;
Rename

2024-11-18 19:04 UTC, MartinSalinas98 commented on src/compute/cuda/cuda_device.hpp
> +    create_device_buffer_copy_shared() override;
Rename

2024-11-18 19:08 UTC, MartinSalinas98 approved these changes

2024-11-18 19:11 UTC, merged